### ISSUE TITLE
Move to-do items to GitHub Issues

### ISSUE THREAD

**Issue by connorgurney** [conorriches/sso#1]
Found this repository through @chris18890's star and am a software developer in Manchester (though not a member of Hack Manchester yet!). Happy to move to-do items that are in code at the moment (per README.md) to here if that helps you track things more easily?

**Comment by conorriches** [comment]
Hey man - sure that is a good idea and would keep things organised! Thanks for your offer of help

I've got a fairly big change coming up which should squash a few TODOs. So I'll be happy to go through them and work out what's still open and what can be closed.

**Comment by connorgurney** [comment]
Sure thing! Would it be easier to wait for you to resolve those that you can with your change, and I can add the rest here?

**Comment by conorriches** [comment]
That sounds good! I'll get it pushed later today! Thanks again for your assistance :)

**Comment by connorgurney** [comment]
No rush, Conor! Looking forward to helping out. 😁
